/**
 * Sprach-Aliase fuer das Industry-Autocomplete (Generator-v3, Spec §14b
 * Punkt 3): Tippen matcht den Alias, die Auswahl setzt IMMER die
 * englische Kanonik-Kategorie aus gmb-categories.ts ins Feld — englische
 * Kategorien funktionieren in jedem Markt (A/B-verifiziert 2026-08-05,
 * Spec §6b), deutsche nur in DACH. Die Aliase sind reine Lookup-Schicht:
 * kein Einfluss auf Query-Bau, language-Hybrid oder Haekchen-Logik.
 *
 * Locale-scoped, damit weitere Sprachen (fr, es, …) reine Daten-Erweiterung
 * sind. Mehrere Aliase pro Kanonik sind erwuenscht (Klempner/Installateur).
 * Integritaets-Garantie: gmb-categories.test.ts prueft, dass jedes
 * Alias-Ziel exakt in GMB_CATEGORIES existiert — Tippfehler = roter Test.
 */

export const CATEGORY_ALIASES: Record<string, Record<string, string>> = {
  de: {
    // Bau + Handwerk
    Generalunternehmer: "General contractor",
    Bauunternehmen: "General contractor",
    Hausbaufirma: "Home builder",
    Dachdecker: "Roofing contractor",
    Klempner: "Plumber",
    Installateur: "Plumber",
    "Sanitärinstallateur": "Plumber",
    Elektriker: "Electrician",
    Elektroinstallateur: "Electrician",
    Klimatechnik: "HVAC contractor",
    Heizungsbauer: "Heating contractor",
    Heizungsinstallateur: "Heating contractor",
    Klimaanlagenbau: "Air conditioning contractor",
    Maler: "Painter",
    Malerbetrieb: "Painter",
    Lackierer: "Painter",
    Tischler: "Carpenter",
    Schreiner: "Carpenter",
    Zimmerei: "Carpenter",
    Bodenleger: "Flooring contractor",
    Parkettleger: "Flooring contractor",
    Fliesenleger: "Tiling contractor",
    Trockenbauer: "Drywall contractor",
    Trockenbau: "Drywall contractor",
    "Dämmtechnik": "Insulation contractor",
    Maurer: "Masonry contractor",
    Betonbauer: "Concrete contractor",
    Betonbau: "Concrete contractor",
    Pflasterer: "Paving contractor",
    "Straßenbau": "Paving contractor",
    Erdarbeiten: "Excavating contractor",
    Baggerbetrieb: "Excavating contractor",
    Abrissunternehmen: "Demolition contractor",
    Abbruchunternehmen: "Demolition contractor",
    Zaunbau: "Fence contractor",
    Terrassenbau: "Deck builder",
    "Küchenstudio": "Kitchen remodeler",
    Badsanierung: "Bathroom remodeler",
    Fensterbauer: "Window installation service",
    Fenstermontage: "Window installation service",
    "Garagentorhändler": "Garage door supplier",
    Glaser: "Glazier",
    Glaserei: "Glazier",
    "Gerüstbau": "Scaffolding service",
    Bauwerksabdichtung: "Waterproofing company",
    Poolbau: "Swimming pool contractor",
    Schwimmbadbau: "Swimming pool contractor",
    Brunnenbau: "Well drilling contractor",
    "Klärgrubenservice": "Septic system service",
    Solaranlagen: "Solar energy company",
    Photovoltaik: "Solar energy company",
    Solarteur: "Solar energy contractor",
    Handwerker: "Handyman",
    "Schlüsseldienst": "Locksmith",
    Schornsteinfeger: "Chimney sweep",
    Dachrinnenreinigung: "Gutter cleaning service",
    "Haushaltsgerätereparatur": "Appliance repair service",
    Aufzugservice: "Elevator service",
    Brandschutz: "Fire protection service",
    Alarmanlagen: "Security system installer",
    Sicherheitstechnik: "Security system installer",
    Baustoffhandel: "Building materials supplier",

    // Haus + Objekt-Services
    Reinigungsfirma: "Cleaning service",
    Reinigungsservice: "Cleaning service",
    Putzfirma: "Cleaning service",
    Haushaltsreinigung: "House cleaning service",
    Gewerbereinigung: "Commercial cleaning service",
    "Büroreinigung": "Commercial cleaning service",
    "Gebäudereinigung": "Janitorial service",
    Teppichreinigung: "Carpet cleaning service",
    Polsterreinigung: "Upholstery cleaning service",
    Fensterputzer: "Window cleaning service",
    Fensterreinigung: "Window cleaning service",
    Hochdruckreinigung: "Pressure washing service",
    "Lüftungsreinigung": "Air duct cleaning service",
    Wasserschadensanierung: "Water damage restoration service",
    Brandschadensanierung: "Fire damage restoration service",
    "Schädlingsbekämpfung": "Pest control service",
    "Kammerjäger": "Pest control service",
    "Garten- und Landschaftsbau": "Landscaper",
    "Landschaftsgärtner": "Landscaper",
    Galabau: "Landscaper",
    Landschaftsarchitekt: "Landscape designer",
    Rasenpflege: "Lawn care service",
    Baumpflege: "Tree service",
    Winterdienst: "Snow removal service",
    Umzugsunternehmen: "Moving company",
    Umzugsfirma: "Moving company",
    "Möbelspedition": "Moving company",
    "Entrümpelung": "Junk removal service",
    "Haushaltsauflösung": "Junk removal service",
    Containerdienst: "Dumpster rental service",
    Selfstorage: "Storage facility",
    Lagerraum: "Storage facility",
    "Bausachverständiger": "Home inspector",
    Baugutachter: "Home inspector",
    Hausmeisterservice: "Property maintenance company",
    "Gebäudemanagement": "Property maintenance company",

    // Auto + Verkehr
    Autowerkstatt: "Auto repair shop",
    "KFZ-Werkstatt": "Auto repair shop",
    Karosseriebau: "Auto body shop",
    Autolackiererei: "Auto body shop",
    Autoglaserei: "Auto glass shop",
    Autohaus: "Car dealer",
    "Autohändler": "Car dealer",
    "Gebrauchtwagenhändler": "Used car dealer",
    Fahrzeugaufbereitung: "Car detailing service",
    Autoaufbereitung: "Car detailing service",
    "Autowäsche": "Car wash",
    Waschanlage: "Car wash",
    "Waschstraße": "Car wash",
    "Reifenhändler": "Tire shop",
    Reifenservice: "Tire shop",
    Getriebewerkstatt: "Transmission shop",
    "Ölwechsel": "Oil change service",
    Autoteilehandel: "Auto parts store",
    Abschleppdienst: "Towing service",
    "Motorradhändler": "Motorcycle dealer",
    Motorradwerkstatt: "Motorcycle repair shop",
    "Wohnmobilhändler": "RV dealer",
    "Wohnwagenhändler": "RV dealer",
    "Bootshändler": "Boat dealer",
    "Anhängerhändler": "Trailer dealer",
    Autovermietung: "Car rental agency",
    Fahrschule: "Driving school",
    "KFZ-Prüfstelle": "Vehicle inspection station",
    Taxiunternehmen: "Taxi service",
    Limousinenservice: "Limousine service",

    // Gesundheit
    Zahnarzt: "Dentist",
    Zahnarztpraxis: "Dentist",
    Zahnklinik: "Dental clinic",
    "Zahnästhetik": "Cosmetic dentist",
    "Kieferorthopäde": "Orthodontist",
    Arzt: "Doctor",
    Arztpraxis: "Doctor",
    MVZ: "Medical clinic",
    Hausarzt: "Family practice physician",
    Allgemeinmediziner: "Family practice physician",
    Kinderarzt: "Pediatrician",
    Hautarzt: "Dermatologist",
    Dermatologe: "Dermatologist",
    "Plastischer Chirurg": "Plastic surgeon",
    "Schönheitschirurg": "Plastic surgeon",
    Chiropraktiker: "Chiropractor",
    Physiotherapeut: "Physical therapist",
    Krankengymnastik: "Physical therapist",
    Physiotherapie: "Physical therapy clinic",
    Ergotherapeut: "Occupational therapist",
    Ergotherapie: "Occupational therapist",
    "Logopäde": "Speech pathologist",
    "Logopädie": "Speech pathologist",
    Podologe: "Podiatrist",
    "Fußpflege": "Podiatrist",
    Akupunktur: "Acupuncturist",
    Heilpraktiker: "Naturopathic practitioner",
    Psychologe: "Psychologist",
    Psychotherapeut: "Psychotherapist",
    Psychotherapie: "Psychotherapist",
    Lebensberatung: "Counselor",
    Augenoptiker: "Optician",
    Optiker: "Optician",
    "Hörakustiker": "Hearing aid store",
    "Hörgeräteakustiker": "Hearing aid store",
    Apotheke: "Pharmacy",
    Kinderwunschklinik: "Fertility clinic",
    Hebamme: "Midwife",
    Pflegedienst: "Home health care service",
    "Ambulanter Pflegedienst": "Home health care service",
    "Betreutes Wohnen": "Assisted living facility",
    Pflegeheim: "Nursing home",
    Altenheim: "Nursing home",
    Seniorenheim: "Nursing home",
    Tierarzt: "Veterinarian",
    Tierarztpraxis: "Veterinarian",

    // Beauty + Wellness
    Kosmetikstudio: "Beauty salon",
    "Schönheitssalon": "Beauty salon",
    Friseur: "Hair salon",
    Friseursalon: "Hair salon",
    "Frisör": "Hair salon",
    Barbier: "Barber shop",
    Nagelstudio: "Nail salon",
    Wellnessstudio: "Spa",
    Massagepraxis: "Massage therapist",
    Masseur: "Massage therapist",
    Massage: "Massage therapist",
    Sonnenstudio: "Tanning salon",
    Solarium: "Tanning salon",
    "Tätowierer": "Tattoo shop",
    Tattoostudio: "Tattoo shop",
    Piercingstudio: "Piercing shop",
    Wimpernstudio: "Eyelash salon",
    Haarentfernung: "Waxing hair removal service",
    "Parfümerie": "Cosmetics store",

    // Fitness + Sport
    Fitnessstudio: "Gym",
    Fitnesscenter: "Fitness center",
    Kampfsportschule: "Martial arts school",
    Boxstudio: "Boxing gym",
    Tanzschule: "Dance school",
    Schwimmschule: "Swimming instructor",
    Sportverein: "Sports club",
    Golfplatz: "Golf club",
    Tennisverein: "Tennis club",

    // Recht + Finanzen + Versicherung
    Anwaltskanzlei: "Law firm",
    Rechtsanwaltskanzlei: "Law firm",
    Kanzlei: "Law firm",
    Rechtsanwalt: "Attorney",
    Anwalt: "Attorney",
    Scheidungsanwalt: "Divorce lawyer",
    "Anwalt für Familienrecht": "Divorce lawyer",
    "Anwalt für Erbrecht": "Estate planning attorney",
    Strafverteidiger: "Criminal justice attorney",
    "Anwalt für Steuerrecht": "Tax attorney",
    "Anwalt für Immobilienrecht": "Real estate attorney",
    Notar: "Notary public",
    Notariat: "Notary public",
    Steuerkanzlei: "Accounting firm",
    "Wirtschaftsprüfer": "Certified public accountant",
    Steuerberater: "Tax consultant",
    Steuerberatung: "Tax consultant",
    Buchhalter: "Bookkeeping service",
    Buchhaltungsservice: "Bookkeeping service",
    "Buchführung": "Bookkeeping service",
    Lohnabrechnung: "Payroll service",
    "Lohnbüro": "Payroll service",
    Finanzplaner: "Financial planner",
    Finanzberater: "Financial consultant",
    "Vermögensberater": "Financial consultant",
    Anlageberatung: "Investment service",
    Versicherungsagentur: "Insurance agency",
    "Versicherungsbüro": "Insurance agency",
    Versicherungsvertreter: "Insurance agency",
    Versicherungsmakler: "Insurance broker",
    Hypothekenmakler: "Mortgage broker",
    Baufinanzierung: "Mortgage broker",
    Baufinanzierer: "Mortgage lender",
    Genossenschaftsbank: "Credit union",
    "Inkassobüro": "Debt collection agency",
    Inkassounternehmen: "Debt collection agency",

    // Immobilien
    "Immobilienbüro": "Real estate agency",
    Immobilienagentur: "Real estate agency",
    Immobilienmakler: "Real estate agent",
    Makler: "Real estate agent",
    Gewerbemakler: "Commercial real estate agency",
    Hausverwaltung: "Property management company",
    Immobilienverwaltung: "Property management company",
    "WEG-Verwaltung": "Property management company",
    "Bauträger": "Real estate developer",
    Projektentwickler: "Real estate developer",
    Immobiliengutachter: "Real estate appraiser",
    Immobilienbewertung: "Real estate appraiser",
    Wohnungsvermittlung: "Apartment rental agency",
    Ferienwohnungsvermittlung: "Vacation home rental agency",
    Ferienwohnungen: "Vacation home rental agency",

    // Business-Services + Kreativ + IT
    Marketingagentur: "Marketing agency",
    Werbeagentur: "Advertising agency",
    "Online-Marketing-Agentur": "Internet marketing service",
    "Online-Marketing": "Internet marketing service",
    "SEO-Agentur": "Internet marketing service",
    Marketingberatung: "Marketing consultant",
    "PR-Agentur": "Public relations firm",
    Grafikdesigner: "Graphic designer",
    Grafiker: "Graphic designer",
    Webdesigner: "Web designer",
    Webdesign: "Web designer",
    Webagentur: "Web designer",
    Softwarefirma: "Software company",
    Softwareunternehmen: "Software company",
    Softwareentwicklung: "Software company",
    "IT-Dienstleister": "IT services",
    "IT-Service": "IT services",
    Systemhaus: "IT services",
    "EDV-Dienstleister": "IT services",
    "IT-Support": "Computer support and services",
    Computerreparatur: "Computer repair service",
    "PC-Reparatur": "Computer repair service",
    "Handy-Reparatur": "Mobile phone repair shop",
    "Smartphone-Reparatur": "Mobile phone repair shop",
    Telekommunikationsanbieter: "Telecommunications service provider",
    Unternehmensberater: "Business management consultant",
    Unternehmensberatung: "Business management consultant",
    Personalberatung: "Human resources consulting",
    "HR-Beratung": "Human resources consulting",
    Headhunter: "Recruiter",
    Personalvermittlung: "Employment agency",
    Arbeitsvermittlung: "Employment agency",
    Zeitarbeitsfirma: "Staffing agency",
    Personaldienstleister: "Staffing agency",
    Callcenter: "Call center",
    "Übersetzer": "Translator",
    "Übersetzungsbüro": "Translator",
    Dolmetscher: "Translator",
    Videoproduktion: "Video production service",
    Filmproduktion: "Video production service",
    Fotograf: "Photographer",
    Fotostudio: "Photography studio",
    Werbefotograf: "Commercial photographer",
    Hochzeitsfotograf: "Wedding photographer",
    Druckerei: "Print shop",
    Copyshop: "Print shop",
    Werbetechnik: "Sign shop",
    Schilderhersteller: "Sign shop",
    Werbeartikel: "Promotional products supplier",
    Werbemittel: "Promotional products supplier",
    Architekt: "Architect",
    "Architekturbüro": "Architect",
    Innenarchitekt: "Interior designer",
    Raumausstatter: "Interior designer",
    "Ingenieurbüro": "Engineering consultant",
    Bauingenieur: "Engineering consultant",
    "Vermessungsbüro": "Land surveyor",
    Vermessungsingenieur: "Land surveyor",
    Umweltberatung: "Environmental consultant",
    Umweltgutachter: "Environmental consultant",
    Gutachter: "Appraiser",
    "Sachverständiger": "Appraiser",
    Sicherheitsdienst: "Security guard service",
    Wachdienst: "Security guard service",
    Objektschutz: "Security guard service",
    Privatdetektiv: "Private investigator",
    Detektei: "Private investigator",
    "Bürogemeinschaft": "Coworking space",
    "Bürobedarf": "Office supply store",
    Schreibwaren: "Office supply store",

    // Logistik + Industrie
    Kurierdienst: "Courier service",
    Botendienst: "Courier service",
    Logistikunternehmen: "Logistics service",
    Spedition: "Freight forwarding service",
    Transportunternehmen: "Trucking company",
    Fuhrunternehmen: "Trucking company",
    Lagerhaus: "Warehouse",
    Lagerhalle: "Warehouse",
    Verpackungsunternehmen: "Packaging company",
    "Außenhandel": "Import export company",
    Zerspanungstechnik: "Machine shop",
    "CNC-Fertigung": "Machine shop",
    Dreherei: "Machine shop",
    Metallbau: "Metal fabricator",
    Schlosserei: "Metal fabricator",
    "Schweißerei": "Welder",
    "Schweißtechnik": "Welder",
    Hersteller: "Manufacturer",
    Produktionsbetrieb: "Manufacturer",
    "Industrieausrüster": "Industrial equipment supplier",
    Baumaschinenvermietung: "Equipment rental agency",
    "Geräteverleih": "Equipment rental agency",
    Recyclinghof: "Recycling center",
    Wertstoffhof: "Recycling center",
    Entsorgungsunternehmen: "Waste management service",
    Abfallentsorgung: "Waste management service",
    "Schrotthändler": "Scrap metal dealer",
    Schrottplatz: "Scrap metal dealer",

    // Gastro + Hotellerie + Events
    "Gaststätte": "Restaurant",
    Gasthaus: "Restaurant",
    Gasthof: "Restaurant",
    Pizzeria: "Pizza restaurant",
    Kaffeehaus: "Coffee shop",
    "Bäckerei": "Bakery",
    "Bäcker": "Bakery",
    Kneipe: "Bar",
    Brauerei: "Brewery",
    Weingut: "Winery",
    Winzer: "Winery",
    Catering: "Caterer",
    Partyservice: "Caterer",
    Foodtruck: "Food truck",
    Eisdiele: "Ice cream shop",
    "Eiscafé": "Ice cream shop",
    Metzgerei: "Butcher shop",
    Fleischerei: "Butcher shop",
    Feinkostladen: "Deli",
    "Frühstückspension": "Bed & breakfast",
    Pension: "Guest house",
    "Gästehaus": "Guest house",
    Jugendherberge: "Hostel",
    Eventlocation: "Event venue",
    Veranstaltungsort: "Event venue",
    Hochzeitslocation: "Wedding venue",
    Festsaal: "Banquet hall",
    Eventagentur: "Event planner",
    Veranstaltungsplaner: "Event planner",
    Hochzeitsplaner: "Wedding planner",
    Veranstaltungstechnik: "Party equipment rental service",
    "Reisebüro": "Travel agency",
    Reiseveranstalter: "Tour operator",

    // Handel
    "Möbelhaus": "Furniture store",
    "Möbelgeschäft": "Furniture store",
    "Matratzengeschäft": "Mattress store",
    "Haushaltsgeräte": "Appliance store",
    "Elektronikgeschäft": "Electronics store",
    Baumarkt: "Hardware store",
    Eisenwarenhandlung: "Hardware store",
    Gartencenter: "Garden center",
    "Gärtnerei": "Garden center",
    Blumenladen: "Florist",
    "Blumengeschäft": "Florist",
    Juwelier: "Jewelry store",
    "Schmuckgeschäft": "Jewelry store",
    Goldschmied: "Jewelry store",
    "Bekleidungsgeschäft": "Clothing store",
    "Modegeschäft": "Clothing store",
    Boutique: "Clothing store",
    "Schuhgeschäft": "Shoe store",
    "Sportgeschäft": "Sporting goods store",
    Fahrradladen: "Bicycle shop",
    "Fahrradgeschäft": "Bicycle shop",
    Buchhandlung: "Bookstore",
    Buchladen: "Bookstore",
    Spielzeugladen: "Toy store",
    "Spielwarengeschäft": "Toy store",
    Geschenkeladen: "Gift shop",
    Tierhandlung: "Pet store",
    Zoohandlung: "Pet store",
    Tierbedarf: "Pet store",
    "Lebensmittelgeschäft": "Grocery store",
    Supermarkt: "Grocery store",
    Kiosk: "Convenience store",
    "Getränkemarkt": "Liquor store",
    Weinhandlung: "Liquor store",
    Spirituosenhandlung: "Liquor store",
    "Musikgeschäft": "Music store",
    Musikhaus: "Music store",
    Kunstgalerie: "Art gallery",
    Galerie: "Art gallery",
    "Antiquitätengeschäft": "Antique store",
    "Antiquitäten": "Antique store",
    "Secondhand-Laden": "Thrift store",
    Gebrauchtwarenladen: "Thrift store",
    Pfandhaus: "Pawn shop",
    Pfandleihhaus: "Pawn shop",

    // Bildung + Betreuung
    Nachhilfe: "Tutoring service",
    Nachhilfeinstitut: "Tutoring service",
    Lernstudio: "Tutoring service",
    Musikschule: "Music school",
    Sprachschule: "Language school",
    Kunstschule: "Art school",
    Flugschule: "Flight school",
    Kindergarten: "Preschool",
    Vorschule: "Preschool",
    Kita: "Day care center",
    "Kindertagesstätte": "Day care center",
    Kinderbetreuung: "Day care center",

    // Tiere + Sonstiges
    Hundefriseur: "Pet groomer",
    Hundesalon: "Pet groomer",
    Tierpension: "Pet boarding service",
    Hundepension: "Pet boarding service",
    Hundetrainer: "Dog trainer",
    Hundeschule: "Dog trainer",
    "Gassi-Service": "Dog walker",
    Hundesitter: "Dog walker",
    Bestattungsunternehmen: "Funeral home",
    Bestatter: "Funeral home",
    Beerdigungsinstitut: "Funeral home",
  },
};
